from search_strategies.best_first_search import BestFirstSearch
from successors import RandomSuccessorFunction


def country_scheduler(self_country_name: str, initial_world_state: dict,
                      output_filename: str, max_best_schedules: int, depth_bound: int,
                      max_frontier_size: int) -> None:

    def successor_fn():
        """
        Returns a list of successor states generated by the generate_random_schedule function.
        """

        sch_gen = RandomSuccessorFunction(self_country_name)

        successors = []
        for _ in range(10):  # Generate 10 successors
            successor = sch_gen.generate_random_schedule(5)
            successors.append(successor)
        return successors

    search = BestFirstSearch()
    best_schedules = search.search(self_country_name, initial_world_state, successor_fn,
                                   depth_bound, max_frontier_size, max_best_schedules)

    ######################################
    # write schedule to file
    ######################################
    # with open(output_filename, 'w') as f:
    #     writer = csv.writer(f)
    #     for i in range(num_output_schedulers):
    # writer.writerow(solution.get_schedule(i))
    # for filename in os.listdir('transformation-templates', 'r'):
    #     template_path = os.path.join(templates_path, filename)
    #     with open(template_path, 'r') as file:
    #         contents = file.read().strip()
    #         transform = Transform(template_path, self.logger)
    #         actions.append(transform_action)
